version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # NATS client connections
      - "8222:8222"  # NATS monitoring
    volumes:
      - ./nats.conf:/etc/nats/nats.conf  # Mount the NATS configuration file
      - nats_data:/data
    command: -c /etc/nats/nats.conf -js -m 8222 -sd /data
    environment:
      - NATS_CONFIG=/etc/nats/nats.conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  nats_data:
  postgres_data:
  redpanda_data:

networks:
  redpanda_network: